### ISSUE TITLE
Bad detection of JWT in Bearer

### ISSUE THREAD

**Issue by cosad3s** [d0ge/sessionless#2]
I have an `Authorization: Bearer JWT` and sessionless cannot detect it as a JWT (enabled in settings: `JWT` and `Unknown`)

Example:

`Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoVGNpQ3dLb3JRdExFX0huek9lcjVLME5GbWlXazQzbEwzdmQyYVZVcWQwIn0.eyJleHAiOjE3MTA5NTk1NDAsImlhdCI6MTcxMDk1OTI0MCwiYXV0aF90aW1lIjoxNzEwOTU0ODI4LCJqdGkiOiJmODhkNWVmZi1jY2RhLTQyNzMtODcyZS1iMDJkZTkzYTYwMzkiLCJ(REDACTED).SIGNATURE`

Detected by sessionless:

- 1 (unknown) - `JmODhkNWVmZi1jY2RhLTQyNzMtODcyZS1iMDJkZTkzYTYwMzkiLCJ(REDACTED).SIGNATURE`
- 2 (unknown) - `eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoVGNpQ3dLb3JRdExFX0huek9lcjVLME5GbWlXazQzbEwzdmQyYVZVcWQwIn0.eyJleHAiOjE3MTA5NTk1NDAsImlhdCI6MTcxMDk1OTI0MCwiYXV0aF90aW1lIjoxNzEwOTU0ODI4LCJqdGkiOi`

**Comment by d0ge** [comment]
Hi @cosad3s can you please try the latest version of the extension. The JWT search function was reworked and it works good for my tests. Unfortunately, your test data is redacted, so it can not be tested.
Cheers

**Comment by cosad3s** [comment]
Thanks! I'll test it asap :)

**Comment by cosad3s** [comment]
On my side, my JWT is not detected anymore.

I have taken a look in the sessionless source code. The involved part is (L448 - `SignedTokenObjectFinder.java`):

```java
if (Arrays.stream(SIGNATURES_LENGTH).noneMatch(x -> x == length)) return Optional.empty();
```

Where `SIGNATURES_LENGTH` is `[20,28,32,48,64]` and my signature size is `256`.

I have questions and suggestions:

- Where/Why did you take these arbitrary values ? Its from a particular RFC or any other document ? As a signature size could be of *any* size (I think), I would suggest to remove this check. I think it was maybe a copy from another token detection function where signature size was important.
- But ... why do not use a dedicated JWT library parser function like [https://github.com/auth0/java-jwt](https://github.com/auth0/java-jwt) ? :+1:  I have made a PR regarding this, in order to stick to the JWT RFC for its detection / parsing with ease (and better performance maybe ?). I have tested it with success (unit tests & burp integration)

**Comment by d0ge** [comment]
Hi @cosad3s,
Thank you so much for your pull request. I've updated it to use existing com.nimbusds.jwt library. The new settings nimbusds was introduced too. 
One thought about signature length, the extension supports only symmetric keys, that's why your JWT wasn't identified. you can try the [JWT Editor](https://github.com/blackberry/jwt-editor) extension for the Asymmetric attacks, I am not planning to add such bruteforce attacks in near future.
Thanks a lot!
Cheers
